name: lstm-caise23
channels:
  - defaults
dependencies:
  - spyder==5.1.5
  - scipy==1.11.4
  - pandas
  - lxml
  - matplotlib
  - nltk
  - scikit-learn
  - ipywidgets
  - pip:
    - hyperopt
    - jellyfish
    - keras==2.15.0
    - pm4py
    - tensorflow==2.15.0
    - opyenxes
    - git+http://github.com/Mcamargo85/support_modules.git
    - swifter==1.4.0
    - minineedle==3.1.5
